package com.vmarket.gateway.config;

// Generated by scripts/generate-search-contract.py; edit docs/search-contract.json.
public final class SearchContract {
	private SearchContract() { }
	public static final String SEARCH_PATH = "/api/ai/search";
	public static final String IMAGE_PATH = "/api/ai/search/image";
	public static final String SUGGESTIONS_PATH = "/api/ai/search/suggestions";
	public static final String HEALTH_PATH = "/api/ai/search/health";
	public static final String SNAPSHOTS_PATH = "/api/products/internal/search-snapshots";
	public static final int MAX_FILE = 10000000;
	public static final int MAX_BODY = 11000000;
	public static final int MAX_IMAGE_PIXELS = 25000000;
	public static final int RESIZE_SHORT_EDGE = 256;
	public static final int MAX_RESIZED_PIXELS = 1048576;
	public static final int EMBEDDING_DIMS = 576;
	public static final String INDEX_PREFIX = "vmarket-products-v1-";
	public static final int MAX_PAGE_SIZE = 100;
	public static final int MAX_RESULT_WINDOW = 10000;
	public static final int MAX_SUGGESTIONS = 20;
	public static final int RETRY_ATTEMPTS = 3;
	public static final String CURRENCY = "VND";
	public static final int UPLOAD_TIMEOUT_SECONDS = 10;
	public static final String IMAGE_TOO_LARGE_CODE = "IMAGE_TOO_LARGE";
	public static final String IMAGE_TOO_LARGE_MESSAGE = "Image upload exceeds limit";
	public static final String RATE_LIMITED_CODE = "RATE_LIMITED";
	public static final String RATE_LIMITED_MESSAGE = "Too many requests";
}
