# Profile PROD - cau hinh qua bien moi truong
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO