"""Generate cross-language Search constants. CI uses --check to reject drift."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def generated_files(values):
    python = '# Generated by scripts/generate-search-contract.py; edit docs/search-contract.json.\n'
    python += '\n'.join(f'{key} = {value!r}' for key, value in values.items()) + '\n'
    yield ROOT / 'services/ai-search-service/contract.py', python
    for service, package in (('api-gateway', 'gateway'), ('product-service', 'product')):
        java = f'package com.vmarket.{package}.config;\n\n'
        java += '// Generated by scripts/generate-search-contract.py; edit docs/search-contract.json.\n'
        java += 'public final class SearchContract {\n\tprivate SearchContract() { }\n'
        for key, value in values.items():
            kind = 'String' if isinstance(value, str) else 'int'
            java += f'\tpublic static final {kind} {key} = {json.dumps(value)};\n'
        java += '}\n'
        yield ROOT / f'services/{service}/src/main/java/com/vmarket/{package}/config/SearchContract.java', java
    path = ROOT / 'frontend/default.conf.template'
    error = {'timestamp': '$time_iso8601', 'status': 413,
             'error': {'code': values['IMAGE_TOO_LARGE_CODE'], 'message': values['IMAGE_TOO_LARGE_MESSAGE']},
             'path': values['IMAGE_PATH']}
    block = f'''    # BEGIN GENERATED SEARCH CONTRACT
    location = {values['IMAGE_PATH']} {{
        client_max_body_size {values['MAX_BODY']};
        client_body_timeout {values['UPLOAD_TIMEOUT_SECONDS']}s;
        resolver ${{NGINX_RESOLVER}} valid=10s ipv6=off;
        set $gateway "${{API_GATEWAY_URL}}";
        proxy_pass $gateway$request_uri;
        proxy_http_version 1.1;
        proxy_connect_timeout 5s;
        proxy_read_timeout 15s;
        proxy_set_header Host $host;
        error_page 413 = @search_too_large;
    }}

    location @search_too_large {{
        default_type application/json;
        return 413 '{json.dumps(error, separators=(',', ':'))}';
    }}
    # END GENERATED SEARCH CONTRACT'''
    text = path.read_text(encoding='utf-8')
    pattern = r'    # BEGIN GENERATED SEARCH CONTRACT.*?    # END GENERATED SEARCH CONTRACT'
    updated, count = re.subn(pattern, lambda _: block, text, flags=re.S)
    if count != 1:
        raise ValueError('Missing nginx generated contract markers')
    yield path, updated
    path = ROOT / 'services/api-gateway/src/main/resources/application.yml'
    text = path.read_text(encoding='utf-8')
    block = (f'# BEGIN GENERATED SEARCH CONTRACT\nspring.servlet.multipart:\n'
             f'  max-file-size: {values["MAX_FILE"]}B\n  max-request-size: {values["MAX_BODY"]}B\n'
             '# END GENERATED SEARCH CONTRACT')
    updated, count = re.subn(r'# BEGIN GENERATED SEARCH CONTRACT.*?# END GENERATED SEARCH CONTRACT',
                            lambda _: block, text, flags=re.S)
    if count != 1:
        raise ValueError('Missing gateway generated contract markers')
    routes = '      # BEGIN GENERATED SEARCH ROUTES\n'
    routes += ''.join(f'      - {values[key]}\n' for key in ('SEARCH_PATH', 'SUGGESTIONS_PATH', 'HEALTH_PATH'))
    routes += '      # END GENERATED SEARCH ROUTES'
    updated, count = re.subn(r'      # BEGIN GENERATED SEARCH ROUTES.*?      # END GENERATED SEARCH ROUTES',
                            lambda _: routes, updated, flags=re.S)
    if count != 1:
        raise ValueError('Missing gateway generated route markers')
    yield path, updated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    values = json.loads((ROOT / 'docs/search-contract.json').read_text(encoding='utf-8'))
    if not 0 < values['MAX_FILE'] < values['MAX_BODY'] or values['RETRY_ATTEMPTS'] < 1:
        raise ValueError('Invalid Search limits')
    stale = []
    for path, expected in generated_files(values):
        actual = path.read_text(encoding='utf-8') if path.exists() else ''
        if actual != expected:
            if args.check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding='utf-8', newline='\n')
    if stale:
        parser.exit(1, 'Search contract drift; run python scripts/generate-search-contract.py:\n' + '\n'.join(stale) + '\n')


if __name__ == '__main__':
    main()
